In [2]:
from scipy.spatial import distance_matrix

array([[1.        , 1.41421356],
       [1.41421356, 1.        ]])

In [8]:
from scipy.stats import spearmanr

SpearmanrResult(correlation=0.9999999999999999, pvalue=nan)

array([[0.29893516]])

In [34]:
import json

with open('../embeddings/low_dim/tfidf_low_dim.json') as f:
    emb1 = json.load(f)
with open('../embeddings/low_dim/bow_low_dim.json') as f:
    emb2 = json.load(f)

with open('../embeddings/low_dim/all_mpnet_base_v2_low_dim.json') as f:
    emb3 = json.load(f)

In [35]:
tf_idf = list(emb1.values())
bw = list(emb2.values())
st = list(emb3.values())

In [42]:
y = spearmanr(tf_idf)
x = spearmanr(bw)
z = spearmanr(st, axis=0)
print(z)

SpearmanrResult(correlation=-0.2821082134689387, pvalue=1.0798801332817158e-05)


In [53]:
import numpy as np

tf = np.array(tf_idf)
np.corrcoef(
    [[3.615783929824829, 0.6], [3.615783929824829, 4.7388763427734375], [3.615783929824829, 4.7388763427734375]])

array([[ 1., -1., -1.],
       [-1.,  1.,  1.],
       [-1.,  1.,  1.]])

In [73]:
from sklearn.metrics import pairwise_distances

with open('../embeddings/low_dim/bow_low_dim.json') as f:
    emb3 = json.load(f)
dist_out = 1 - pairwise_distances(list(emb3.values()), metric="cosine")
dist_out
x = [np.mean(i) for i in dist_out]
print(np.mean(x))

0.9512869000486365


In [75]:
from sklearn.metrics.pairwise import euclidean_distances
from scipy import sparse
import numpy as np

In [82]:
from sklearn.metrics import pairwise_distances

with open('../embeddings/low_dim/all_minilm_l6_v2_low_dim.json') as f:
    emb4 = json.load(f)
A_sparse = sparse.csr_matrix(list(emb4.values()))

similarities = euclidean_distances(A_sparse)
print('pairwise dense output:\n {}\n'.format(similarities))
x = [np.mean(i) for i in similarities]
print(np.mean(x))

pairwise dense output:
 [[0.         1.22980762 3.60351788 ... 1.88893592 4.53601834 3.12138608]
 [1.22980762 0.         4.50609573 ... 1.38141213 3.4005609  2.46430274]
 [3.60351788 4.50609573 0.         ... 5.49160012 7.87173139 4.48775307]
 ...
 [1.88893592 1.38141213 5.49160012 ... 0.         2.99167812 3.77257957]
 [4.53601834 3.4005609  7.87173139 ... 2.99167812 0.         4.38436745]
 [3.12138608 2.46430274 4.48775307 ... 3.77257957 4.38436745 0.        ]]

4.120552450667069


{'Image Registration Methods for Patient-Specific Virtual Physiological Human Models': [6.912987232208252, 6.957751750946045], 'Interactive Classification of Multi-Shell Diffusion MRI With Features From a Dual-Branch CNN Autoencoder': [3.9920718669891357, 8.8130464553833], 'Visual Assessment of Vascular Torsion using Ellipse Fitting': [7.381600856781006, 4.968464374542236], 'Simulation-based Ultrasound Training Supported by Annotations, Haptics and Linked Multimodal Views': [7.512796878814697, 7.794095516204834], 'How to Evaluate Medical Visualizations on the Example of 3D Aneurysm Surfaces': [5.741652965545654, 9.104303359985352], 'Student and Teacher Meet in a Shared Virtual Reality: A one-on-one Tutoring System for Anatomy Education': [7.218874454498291, 9.966750144958496], 'CT Late Enhancement Segmentation for the Combined Analysis of Coronary Arteries and Myocardial Viability': [6.275537014007568, 4.54205846786499], 'Estimation of the Midsagittal Plane for Sideness Determination o